services:
  pgvector:
    image: "pgvector/pgvector:pg16"
    env_file:
      - env.localdev
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.localdev
    env_file:
      - env.localdev
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "JWT_SECRET=${JWT_SECRET}"
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "8000:8000"
    depends_on:
      - "pgvector"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.localdev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - node_modules:/app/node_modules
    env_file:
      - env.localdev
    depends_on:
      - "backend"

volumes:
  node_modules:
  postgres_data:
